# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e20721a5f5a4af222efb0a03f5d79667d16ca06d630d2c82efa1b7ed2c22010b846b77658bcec40708938dea749f1a0782ecfd6132f253a1c7dc1190720476b9

test:
  secret_key_base: 2d9e69c73525a866c414cd497094e661da5101e2e016b8f6299159a375bde17184c416c9afc63213eae4360debfdb4564eea7d313ecc2ba80067515c9fe513ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
